name: build and publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies and lint
        run: |
          cd src
          npm install
      - name: Get Next Release Tag
        id: get_latest_release
        run: |
          git fetch --force --tags
          latestTag=$(git tag --list 'v*' --sort=-version:refname | head -n 1)
          latestTag=${latestTag:-v0.0.0}
          echo "Latest tag: $latestTag"
          latestTag=${latestTag#\"}
          latestTag=${latestTag%\"}
          latestTag=${latestTag#v}

          IFS='.' read -r major minor patch <<< "$latestTag"
          major=${major:-0}
          minor=${minor:-0}
          patch=${patch:-0}

          newTag="v${major}.$((minor + 1)).0"
          echo "result=$newTag" >> "$GITHUB_OUTPUT"

      - name: zip dist
        run: |
          cd src
          zip -r ../dist.zip .
      - name: Publish to GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: dist.zip
          body: Automated release of ${{ steps.get_latest_release.outputs.result }}
          tag: ${{ steps.get_latest_release.outputs.result }}
